SELECT qti.TIS_ID_COMERCIAL, qti.TQI_CODIGO, qti.TIS_CLIENTE_TERMINAL
FROM 
    SIGITM_1_2.QRY_SISMGP_TI qti
    JOIN SIGITM_1_2.tbl_ti ti ON qti.TQI_CODIGO = ti.TQI_CODIGO
WHERE 
	qti.TQI_CODIGO = {{bd}}